# Generated by Django 5.2.6 on 2025-09-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("publisher", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "books",
            },
        ),
    ]
