# Generated by Django 5.2.6 on 2025-09-17 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("SubjectCode", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("credits", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("TeacherID", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("qualification", models.CharField(max_length=50)),
                (
                    "subjectcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firstapp.subject",
                    ),
                ),
            ],
        ),
    ]
