# Generated by Django 5.2.6 on 2025-09-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0002_subject_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="subjectcode",
        ),
        migrations.AddField(
            model_name="subject",
            name="teacher",
            field=models.ManyToManyField(to="firstapp.teacher"),
        ),
    ]
