# Generated by Django 5.2.6 on 2025-09-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0003_remove_teacher_subjectcode_subject_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="ebook",
            field=models.BooleanField(default=True),
        ),
    ]
